language: clojure

cache:
  directories:
    - $HOME/.m2

before_install:
  - "curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh"
  - "chmod +x linux-install-1.10.1.466.sh"
  - "sudo ./linux-install-1.10.1.466.sh"
  - "clojure -Sdescribe"

script: lein test

notifications:
  email:
    on_failure: change
