language: java

sudo: required

services:
  - docker

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

before_script:
  - sudo /etc/init.d/postgresql stop

script: ./mvnw clean verify

after_success:
  - ./mvnw coveralls:report

notifications:
  email:
    on_failure: change
